### PR TITLE
feat(RHTAPREL-806): update operator toolkit refrence

### PR DESCRIPTION
**Pull request by happybhati**
This commit updates the `operator-toolkit` refrence
 as result of migration to `konflux-ci` from `redhat-appstudio`
 more details parent EPIC:
 https://issues.redhat.com/browse/RHTAPREL-800

## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered ([check the PR coverage on codecov](https://app.codecov.io/gh/redhat-appstudio/integration-service/pulls))
- [ ] [Controllers diagrams](https://github.com/redhat-appstudio/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

### CODE REVIEW

**Comment by happybhati** [comment]
`Do Not Merge/Hold` preparation PR, Can be merged once repo is migrated to `konflux-ci`!

**Comment by happybhati** [comment]
CI failing due to high severity CVE causing an EC failure.
Jira for the issue: https://issues.redhat.com/browse/EC-520

**Comment by MartinBasti** [comment]
We updated repo to use vendoring, please rebase and update deps accordingly, thanks!

https://github.com/redhat-appstudio/integration-service/blob/main/README.md#addingupdating-a-dependency

**Comment by jsztuka** [comment]
Can we help with this somehow?

**Comment by happybhati** [comment]
> Can we help with this somehow?

I believe this PR is blocked by https://issues.redhat.com/browse/STONEINTG-893 
It would be great if someone could take that issue.

**Comment by happybhati** [comment]
[@MartinBasti @dirgim ]
Can I get some review, please?
Many thanks for all your help.

**Review by jsztuka — APPROVED** [review]

**Review by dheerajodha — APPROVED** [review]

**Review by hongweiliu17 — APPROVED** [review]

**Pull request merged**
