### PR TITLE
feat(STONEINTG-968): use go 1.22

### PR DESCRIPTION
**Pull request by jsztuka**
## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered ([check the PR coverage on codecov](https://app.codecov.io/gh/konflux-ci/integration-service/pulls))
- [ ] [Controllers diagrams](https://github.com/konflux-ci/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

### CODE REVIEW

**Comment by jsztuka** [comment]
It's little suspitions that go.sum has no changes in it.

**Review by kasemAlem — APPROVED** [review]

**Comment by kasemAlem** [comment]
LGTM

**Comment by jsztuka** [comment]
Currently testing changes on local, so far everything integration-service related stuff is working.

**Comment by kasemAlem** [comment]
flaky tests , retesting 
/retest

**Comment by jsztuka** [comment]
Local testing passed the tests, creating ITS, running build-def pipelinerun to create snapshot.

**Comment by jsztuka** [comment]
It seems like flaky isse when I look at e2e test, can someone confirm?
`Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"dora-metrics\"},\"spec\":{},\"status\":{}}\n"},"creationTimestamp":null,"labels":null}}
to:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "dora-metrics", Namespace: ""
for: "STDIN": error when patching "STDIN": Internal error occurred: failed calling webhook "namespace.operator.tekton.dev": failed to call webhook: Post "https://tekton-operator-proxy-webhook.openshift-pipelines.svc:443/namespace-validation?timeout=10s": no endpoints available for service "tekton-operator-proxy-webhook"
Error: reached maximum number of attempts (2). error: exit status 1
make: *** [Makefile:25: ci/test/e2e] Error 1
./mage -v ci:unregisterSprayproxy
Running target: CI:UnregisterSprayproxy
I1209 13:19:11.628164   23882 magefile.go:1113] Before unregistering pac server...
I1209 13:19:11.831460   23882 magefile.go:1142] The PaC servers registered in Sprayproxy:  https://pipelines-as-code-controller-openshift-pipelines.apps.rosa.jinqi1017.eadb.p3.openshiftapps.com, https://pipelines-as-code-controller-openshift-pipelines.apps.ci-op-zwih4w9b-8a7d4.rhtap-perfscale.devcluster.openshift.com, https://pipelines-as-code-controller-openshift-pipelines.apps.rosa.kx-6e2b82814e.5zel.p3.openshiftapps.com
W1209 13:19:11.873827   23882 utils.go:435] failed to unregister SprayProxy: failed to get PaC host: routes.route.openshift.io "pipelines-as-code-controller" not found - this issue will be reported to a dedicated Slack channel
Skipped pulling layers without file name in "org.opencontainers.image.title"`

**Comment by jsztuka** [comment]
Alright, now it seems like the legit error:
[FAILED] [1.205 seconds]
[integration-service-suite Integration Service E2E tests] with happy path for general flow of Integration service [AfterAll] when An snapshot of push event is created checks if a Release is created successfully [integration-service]
  [AfterAll] /tmp/tmp.kfWCutneqd/tests/integration-service/integration.go:63
  [It] /tmp/tmp.kfWCutneqd/tests/integration-service/integration.go:226

  Start to delete component 'test-component-pac-mrazsy' at 2024-12-09T13:35:21Z
  Finish to delete component 'test-component-pac-mrazsy' at 2024-12-09T13:35:22Z. It took '0.017315' minutes
  [FAILED] in [AfterAll] - /tmp/tmp.kfWCutneqd/tests/integration-service/integration.go:67 @ 12/09/24 13:35:22.359
 

>  [FAILED] Expected success, but got an error:

      <*errors.StatusError | 0xc0002a4000>: 
      snapshots.appstudio.redhat.com "snapshot-sample-ncjy" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "snapshots.appstudio.redhat.com \"snapshot-sample-ncjy\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "snapshot-sample-ncjy",
                  Group: "appstudio.redhat.com",
                  Kind: "snapshots",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  In [AfterAll] at: /tmp/tmp.kfWCutneqd/tests/integration-service/integration.go:67 @ 12/09/24 13:35:22.359

> Summarizing 1 Failure:

  [FAIL] [integration-service-suite Integration Service E2E tests] with happy path for general flow of Integration service [AfterAll] when An snapshot of push event is created checks if a Release is created successfully [integration-service]
  /tmp/tmp.kfWCutneqd/tests/integration-service/integration.go:67

**Comment by jsztuka** [comment]
I will need to look into te error on IS side.

**Comment by jsztuka** [comment]
And new error arised:
`{"error": "time=\"2024-12-10T11:18:02Z\" level=fatal msg=\"Error parsing image name \\\"docker://quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:bdb188a1f3ce1d0565fe84387b6d00826041300702e306542d85715a24d3514e\\\": can't talk to a V1 container registry\"\n"}
Images processed:
{'image': {'pullspec': 'quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service:on-pr-cc44ad333f443cff7c43b1e9cc78bc2e37e30e74', 'digests': ['sha256:bdb188a1f3ce1d0565fe84387b6d00826041300702e306542d85715a24d3514e']}}`

**Comment by jsztuka** [comment]
Not sure but the failing task has been updated ~20 hours ago:
https://quay.io/repository/redhat-appstudio/tools?tab=tags

**Comment by jsztuka** [comment]
Intermittent failure.

**Comment by kasemAlem** [comment]
@jsztuka , 
we need to retest so it failed on flaky one 
/retest

**Comment by jsztuka** [comment]
Praying for the gods so the CI passes.

**Comment by jsztuka** [comment]
I have a bad feeling that we need to address the issue from e2e :/

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
