### PR TITLE
fix(STONEINTG-999): annotate snapshot for unrecoverable error

### PR DESCRIPTION
**Pull request by hongweiliu17**
* annotation component snasphots when meeting unrecoverable error during group snapshot creation

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered ([check the PR coverage on codecov](https://app.codecov.io/gh/redhat-appstudio/integration-service/pulls))
- [ ] [Controllers diagrams](https://github.com/konflux-ci/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

### CODE REVIEW

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by jencull — APPROVED** [review]
lgtm

**Review by jencull — COMMENTED** [review]
/retest

**Comment by kasemAlem** [comment]
failed with proxy connection , 
`failed to unregister SprayProxy: failed to get PaC host: routes.route.openshift.io "pipelines-as-code-controller" not found `

will give another try , it could be network issue

**Pull request merged**
