### PR TITLE
fix: update task-summary image to newest version

### PR DESCRIPTION
**Pull request by dirgim**
Signed-off-by: dirgim <kpavic@redhat.com>

## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered ([check the PR coverage on codecov](https://app.codecov.io/gh/konflux-ci/integration-service/pulls))
- [ ] [Controllers diagrams](https://github.com/konflux-ci/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

### CODE REVIEW

**Review by kasemAlem — APPROVED** [review]

**Comment by kasemAlem** [comment]
LGTM

**Comment by kasemAlem** [comment]
@dirgim it failed on same issue as Jiri's one , I'll look into it

**Review by Josh-Everett — APPROVED** [review]
LGTM - assuming spurious failure

**Comment by dirgim** [comment]
Closing in favor of #950 which now contains the same update.

**Pull request closed without merging**
